#:kivy 1.9.1

# Copyright (C) 2019  Mariano Ramis

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:import BoolOption gui.configw.BoolOption
#:import FloatOption gui.configw.FloatOption
#:import IntegerOption gui.configw.IntegerOption
#:include gui/configw.kv

#:set pannel_text_height 30
#:set pannel_spacing 25
#:set pannel_padding 5


<Sections>:
  vu_buttons: {}
  do_default_tab: False
  TabbedPanelItem:
    text: "Video"
    VideoSubSection
      vu_buttons: root.vu_buttons

  TabbedPanelItem:
    text: "Explorer"
    ExplorerSubSection:
      vu_buttons: root.vu_buttons

  TabbedPanelItem:
    text: "Kinematics"
    KinematicsSubSection:
      vu_buttons: root.vu_buttons

<VideoSubSection>:
  rows: 3
  cols: 1
  config: app.usrconfig

  spacing: pannel_spacing
  padding: pannel_padding
  row_force_default: True
  row_default_height: pannel_text_height

  GridLayout:  # Seleccionar dispositivo.
    rows: 1
    cols: 2
    spacing: 5
    row_force_default: True
    row_default_height: pannel_text_height
    Label:
      text: "seleccionar dispositivo:"
      halign: "left"
      valign: "center"
      text_size: self.size
      size_hint_x: 0.6
    Spinner:
      id: device
      text: root.config.get("video", "device")
      values: ["webcam", "usb_camera"]
      on_text: root.setDevice(self.text)

  GridLayout:  # Nombre del archivo de video a capturar.
    rows: 2
    cols: 1
    spacing: 5
    row_force_default: True
    row_default_height: pannel_text_height
    Label:
      text: "ingresar nombre del archivo de video:"
      halign: "left"
      text_size: self.size
    TextInput:
      id: videoname
      multiline: False
      on_text_validate: root.setVideoName(self.text)

  GridLayout:  # Configuración de captura.
    rows:
    cols: 2
    spacing: pannel_spacing + 30
    padding: [0, pannel_padding + 30, 0, 0]
    row_force_default: True
    row_default_height: pannel_text_height
    IntegerOption:
      label: u"Umbral de blanco"
      section_variable: "image:threshold"
      option_values: [200, 255, 1]
    BoolOption:
      label: u"Expandir detección"
      section_variable: "image:dilate"
    IntegerOption:
      label: u"Iteraciones de dilatación"
      section_variable: "image:dilate_iterations"
      option_values: [3, 10, 1]
    IntegerOption:
      label: u"Escala de dilatación"
      section_variable: "image:dilate_kernel_size"
      option_values: [3, 11, 2]



<ExplorerSubSection>:
  config: app.usrconfig


<KinematicsSubSection>:
  config: app.usrconfig
