#:kivy 1.9.1

# Copyright (C) 2017  Mariano Ramis

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#:import StringProperty kivy.properties.StringProperty

<MainFrame>:
    # Nombre del archivo fuente
    cols:1
    rows: 4

    sourcefile: None
    config: app.config

    FloatLayout:
        size_hint: 1, 0.3
        Label:
            id: sourcefile
            variable: StringProperty(None)

    GridLayout:
        cols: 2
        size_hint: 1, 0.5

        GridLayout:
            cols: 1
            size_hint_x: 0.3
            Button:
                text: 'Nuevo'
                on_release: root.show_load()
            Button:
                text: 'Visualizar'
                on_release: root.video_preview()
            Button:
                text: 'Explorar'
                on_release: root.video_explorer()

        FloatLayout:
            size_hint_x: 0.7
            UserInput:

    # Presentación de resultados.
    Outcomes:
        size_hint: (1, 1)
        id: outcomes
    # Consola de control: 2da sección.
    # Boton de generar graficos.
    GridLayout:
        cols:2
        size_hint: (1, 0.3)
        FloatLayout:
            Button:
                text: 'Graficar'
                on_release: root.ids['outcomes'].plot(root.sourcefile, root.sac)


<UserInput@TabbedPanel>:
    TabbedPanelItem:
        text: 'Sesion'
    TabbedPanelItem:
        text: "Explorador"
    TabbedPanelItem:
        text: "Visualizador"
    TabbedPanelItem:
        text: u"Cámara"
    TabbedPanelItem:
        text: "Ciclos"
    TabbedPanelItem:
        text: u"Gráficos"


<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            rootpath: root.source
        BoxLayout:
            size_hint_y: None
            height: 50
            Button:
                text: "Seleccionar"
                on_release: root.load(filechooser.path, filechooser.selection)


<Outcomes>:
    cols: 2
    GridLayout:
        cols:1
        Label:
            text: 'Cyclos Izquierdos'
        ScrollView:
            size_hint: 1, None
            GridLayout:
                id: leftside
                cols: 1
                size_hint_y: None
                height: self.minimum_height
                row_default_height: 30
    GridLayout:
        cols:1
        Label:
            text: 'Cyclos Derechos'
        ScrollView:
            size_hint: 1, None
            GridLayout:
                id: rightside
                cols: 1
                size_hint_y: None
                height: self.minimum_height
                row_default_height: 30


<Cycle>:
    cols: 2
    CheckBox:
        id: check
        active: True
    Label:
        id: label
